### ISSUE TITLE
Release script that ensures the correct migration number is provided

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lnschema-core#44]
Might be very important unless we find another solution:

- https://github.com/laminlabs/lnschema-core/commit/d1c3fe3ad44f104c214e510d5dfe8c6f6af39c64

**Comment by falexwolf** [comment]
OK, so we can fix the current problem (see commit above) by manually removing the wrong migration that was written here:

https://github.com/laminlabs/lndb-setup/blob/409cccb2f0c1677da497db4277c16216f9db9e7d/lndb_setup/_db.py#L106-L108

We can avoid writing a migration number if there is any query result on the `migration_XXXX` table. This will avoid that there is ever a wrong migration number written.

Maybe we can avoid storing `_migration` completely, which would be great as we'd then eliminate all danger for error due to redundancy.

**Comment by falexwolf** [comment]
OK, so this should fix the issue for existing auto-migrating instances; the problem we just encountered:

- https://github.com/laminlabs/lndb-setup/pull/71

However, an inconsistent version string will still affect new instances, and make them impossible to migrate.

**Comment by falexwolf** [comment]
@fredericenard, could you rerun CI here after fixing the corrupted postgres instance?

- https://github.com/laminlabs/lndb-setup/pull/71

The PR seems to be good otherwise.

**Comment by sunnyosun** [comment]
@falexwolf Is this still needed?
